### ISSUE TITLE
Licensing issues / adding this to an Apache licensed software

### ISSUE THREAD

**Issue by cdrage** [novln/docker-parser#1]
Hi @novln !

You recommend that we either fork or copy the code into our own project.

I like this parser since there are a TON of different cases for parsing within Docker (it's quite a nuisance!)

I can fork no problems.

Ideally.. I'd like to copy this code into a project I contribute to (https://github.com/kubernetes-incubator/kompose) and continue to further improve this parser.

Unfortunately there's a licensing issue... GPLv3 isn't compatible with the Apache license and thus we can't add it.

It's a long-shot, but is it possible to change the licensing to Apache v2 and/or give explicit permission that we're allowed to use your library?

Many thanks :tada:  :tada:  :tada:

**Comment by novln** [comment]
Hi Charlie,

First of all, thank you for these kind words.

I'm okay changing the license to Apache v2 and also to transfer this repo to your organization.
Since I won't be able to maintain this parser as it should, I think it's best if more people can contribute to it.

If you like that idea, or not, don't hesitate to reply :)

**Comment by cdrage** [comment]
Hi @novln thank you so much for changing the licensing!!

I can't transfer this repo to the @kubernetes-incubator org, but if you wish, I can transfer it to my own username and then I can continue to work on it (with the help from the @kubernetes-incubator/kompose team. It's up to you!

We we're originally intending to simply grab this code and copy it into ours, but it may be best to keep it modular and separated so other users (like myself who found this!) can continue to!

**Comment by novln** [comment]
Hi @cdrage,

I've changed the license and also made you a collaborator.
Feel free to push any refactor/feature that you find necessary.

See ya'

**Comment by cdrage** [comment]
@novln Awesome! Thank you! :)
